### ISSUE TITLE
kz_bhop_watertemple

### ISSUE THREAD

**Issue by Zpamm** [Metapyziks/SourceUtils#21]
https://rutoc.me/Replays?map=kz_bhop_watertemple&mode=1&type=0
missing textures, supposed to be water and then blocks on top of water throughout the start of the map

**Comment by Metapyziks** [comment]
The missing textures on the blocks are `fragtex/wood panel05.vtf`, which just isn't in the pakfile at all. I don't know where CS:GO loads it from 😕

**Comment by Metapyziks** [comment]
Fixed, the missing texture was causing an error that meant other materials weren't loading.
