### ISSUE TITLE
bkz_levite_ng

### ISSUE THREAD

**Issue by Zpamm** [Metapyziks/SourceUtils#23]
https://rutoc.me/Replays?map=bkz_levite_ng&mode=2&type=0#t7510
around 55-56 seconds in this replay, there's a bhop block lower to the left of where he is, i think the block falls down when you jump on it, but kztimer does something to stop that and gokz doesnt, but in the replay the blocks non existent. You can also see it in this video https://www.youtube.com/watch?v=RSPxRqE3Ovs at about 1:22, the square block in the middle.

**Comment by Metapyziks** [comment]
Fixed
