### ISSUE TITLE
bkz_nocturns_blue

### ISSUE THREAD

**Issue by Zpamm** [Metapyziks/SourceUtils#24]
https://rutoc.me/Replays?map=bkz_nocturns_blue&mode=1&type=1
whole map looks pitch black, it's supposed to be pitch black but have a blue glow/outline on the blocks and the walls so you know where you're, for an example see https://www.youtube.com/watch?v=ytU0rVsCtWo.

**Comment by Metapyziks** [comment]
Fixed
