### ISSUE TITLE
Entity properties with matching keys being overwritten/not included

### ISSUE THREAD

**Issue by Chabinka** [Metapyziks/SourceUtils#59]
Entities can have multiple outputs with the same key name, i.e. OnTrigger

![Image](http://crayz.tv/files/sharex/javaw_2019-02-12_10-30-45.png)

https://github.com/Metapyziks/SourceUtils/blob/193d0eb5e66ddf504585cd0aa21698d2d7e57b21/SourceUtils/ValveBsp/EntityLump.cs#L325-L339

**Comment by Metapyziks** [comment]
Thanks for reporting!
